# Install all required dependencies
- name: install all rquired depencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
    - python-mysqldb
